### ISSUE TITLE
some question about the code

### ISSUE THREAD

**Issue by eriche2016** [zyh16143998882/AAAI24-PointFEMAE#1]
hi， nice work, and congrats. 
I have some questions bout PointMAE.py.
can you give some explanations and tell us the differences between the following classesss defined in the code
1) three blocks: Block, BlockH, BlockH_ALL
2) threetransformerrencodersr: TransformerEncoder, TransformerEncoderH, TransformerEncoderH_ALL
3) four mask transformer: MaskTransformerLEM, MaskTransformerH, MaskTransformerH_GEM, MaskTransformerH_ALL
4) five PointMAE versions: Point_MAE, Point_MAE_LEM, Point_FEMAE, Point_FEMAE_ALL
5) four point transformers: PointTransformer, PointTransformerHMAERaw, PointTransformerHMAE

It would help a lot if you gave some hints. 

Besides, I also found that some classes are really similar, for example, MaskTransformerH and MaskTransformerH_GEM except that one uses masked_center_rand and the other uses masked_center_block.

**Comment by zyh16143998882** [comment]
Thank you for your attention! Yes, these different modules are very similar, and they are used to do ablation studies. You can refer to "Effect of Different Architectures and Designs" in the appendix of the paper for details.

**Comment by eriche2016** [comment]
Thanks for your promptly reply.
