### ISSUE TITLE
Question about `finetune_hard.py`

### ISSUE THREAD

**Issue by xuweigogogo** [zyh16143998882/AAAI24-PointFEMAE#5]
Thanks for your excellent work! Sorry for bothering you during your vacation.

I noticed in your code there is a `finetune_hard.py` and `--hard` argument. Is it used for fine-tuning `PB-T50-RS`?

Will this augmentation improve results?

**Comment by zyh16143998882** [comment]
This adds simple scaling to simple rotation, and in fact this augmentation gives some improvement, but it's so slight that you can replace the PT-RS-50 with simple rotation to verify it further.

**Comment by xuweigogogo** [comment]
Thanks for your quick reply.
I wonder if the `PB-T50-RS` results in the paper use `PointcloudScaleAndTranslate` as an additional data augmentation?

**Comment by zyh16143998882** [comment]
it uses the following data augmentation:
{
data_transforms.PointcloudScaleAndTranslate(scale_low=0.9, scale_high=1.1, translate_range=0),
data_transforms.PointcloudRotate(),
}
"translate_range=0", so it only involves using PointcloudRotate after a simple scaling between [0.9, 1.1].

**Comment by xuweigogogo** [comment]
> it uses the following data augmentation: { data_transforms.PointcloudScaleAndTranslate(scale_low=0.9, scale_high=1.1, translate_range=0), data_transforms.PointcloudRotate(), } "translate_range=0", so it only involves using PointcloudRotate after a simple scaling between [0.9, 1.1].

Thanks for the clarification. Can you confirm if this combined data augmentation is exclusive to `PB-T50-RS`, or is it also utilized in all three variants of ScanObjectNN?

**Comment by zyh16143998882** [comment]
There is no clear improvement on objbg and objonly, in fact this improvement 'PointcloudScaleAndTranslate(scale_low=0.9, scale_high=1.1, translate_range=0)' is also relatively slight in PT-RS-50. Major improvements rely on 'PointcloudRotate()'.

**Comment by xuweigogogo** [comment]
Thanks for your reply. It is a useful suggestion. I will have a try.
