### ISSUE TITLE
From scratch

### ISSUE THREAD

**Issue by BooguTeam** [zyh16143998882/AAAI24-PointFEMAE#6]
Hi,

Thanks for the great work. I have a little question (Not nitpick, I knew it's a pretrain work):
I train the FEMAE from scratch, but the network performance is poor, can you provide some possible reasons/insights for it?
ScanObject-background: 77.2805
cmd: CUDA_VISIBLE_DEVICES=0 python main.py --config cfgs/finetune_scan_objbg_femae.yaml --finetune_model --exp_name bg_femae

**Comment by Harr7y** [comment]
Sorry, my fault.
